export const Images = [
    {
      id: "1",
      author: "John Doe",
      download_url: "https://source.unsplash.com/800x600/?superhero",
      tags: ["superhero", "action"],
      memory: "A superhero in action",
    },
    {
      id: "2",
      author: "Jane Doe",
      download_url: "https://source.unsplash.com/800x600/?nature",
      tags: ["nature", "landscape"],
      memory: "A scenic natural landscape",
    },
    {
      id: "3",
      author: "Bob Smith",
      download_url: "https://source.unsplash.com/800x600/?technology",
      tags: ["technology", "innovation"],
      memory: "Cutting-edge technology",
    },
    {
      id: "4",
      author: "Alice Johnson",
      download_url: "https://source.unsplash.com/800x600/?galaxy",
      tags: ["galaxy", "space"],
      memory: "A mesmerizing galaxy",
    },
    {
      id: "5",
      author: "Eve Green",
      download_url: "https://source.unsplash.com/800x600/?space",
      tags: ["space", "cosmos"],
      memory: "A cosmic adventure",
    },
    {
      id: "6",
      author: "Sam Brown",
      download_url: "https://source.unsplash.com/800x600/?technology",
      tags: ["technology", "futuristic"],
      memory: "Future technology in action",
    },
    {
      id: "7",
      author: "Chris Black",
      download_url: "https://source.unsplash.com/800x600/?metaverse",
      tags: ["metaverse", "virtual reality"],
      memory: "Exploring the metaverse",
    },
    {
      id: "8",
      author: "Olivia White",
      download_url: "https://source.unsplash.com/800x600/?nature",
      tags: ["nature", "wildlife"],
      memory: "A captivating wildlife scene",
    },
    {
      id: "9",
      author: "David Gray",
      download_url: "https://source.unsplash.com/800x600/?technology",
      tags: ["technology", "cyber"],
      memory: "Cybernetic technology",
    },
    {
      id: "10",
      author: "Sophia Taylor",
      download_url: "https://source.unsplash.com/800x600/?superhero",
      tags: ["superhero", "comics"],
      memory: "A classic comic book superhero",
    },
    {
      id: "11",
      author: "Mike Johnson",
      download_url: "https://source.unsplash.com/800x600/?tech",
      tags: ["technology", "digital"],
      memory: "Digital technology",
    },
    {
      id: "12",
      author: "Emily Green",
      download_url: "https://source.unsplash.com/800x600/?forest",
      tags: ["nature", "forest"],
      memory: "A serene forest",
    },
    {
      id: "13",
      author: "Alex Brown",
      download_url: "https://source.unsplash.com/800x600/?stars",
      tags: ["galaxy", "stars"],
      memory: "Starry night",
    },
    {
      id: "14",
      author: "Sarah White",
      download_url: "https://source.unsplash.com/800x600/?robot",
      tags: ["technology", "robotics"],
      memory: "Advanced robotics",
    },
    {
      id: "15",
      author: "Tom Gray",
      download_url: "https://source.unsplash.com/800x600/?universe",
      tags: ["space", "universe"],
      memory: "Vast universe",
    },
    {
      id: "16",
      author: "Jessica Taylor",
      download_url: "https://source.unsplash.com/800x600/?code",
      tags: ["technology", "code"],
      memory: "Lines of code",
    },
    {
      id: "17",
      author: "Chris Johnson",
      download_url: "https://source.unsplash.com/800x600/?cyberspace",
      tags: ["metaverse", "cyberspace"],
      memory: "Journey in cyberspace",
    },
    {
      id: "18",
      author: "Emma Doe",
      download_url: "https://source.unsplash.com/800x600/?mountain",
      tags: ["nature", "mountain"],
      memory: "Majestic mountains",
    },
  ];
  