import Footer from './components/footer'
import Navbar from './components/navbar'
import './globals.css'
import { DM_Sans } from 'next/font/google'

const inter = DM_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {

  // const options = {
  //   method: 'GET',
  //   headers: {
  //     accept: 'application/json',
  //     Authorization: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlOWU3MmVhYTJjM2FjNjQxOTI5MDUwMWRhMmIxMGRlNSIsInN1YiI6IjY0ZmUyNzdjZWZlYTdhMDBjMzk1ODUxMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.TncS0a3jc6jBVRUjwryn759KzTr2kMjmJs5N4IBzvCw'
  //   }
  // };
  
  // fetch('https://api.themoviedb.org/3/authentication', options)
  //   .then(response => response.json())
  //   .then(response => console.log(response))
  //   .catch(err => console.error(err));
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-full ">
       

<div className="">


        {children}
</div>

<div className="bottom-0 justify-end">

<Footer />
</div>
        </div>
        
        </body>
    </html>
  )
}
